// `locke <path>` command-line entry.
//
// Locke can be launched from a terminal like `code .` / `zed .`. A tiny shim at
// ~/.local/bin/locke execs THIS app binary directly with the target directory
// (not via `open -a`, which wouldn't forward args to a running instance). On a
// cold launch the path is read from argv and handed to the frontend; while Locke
// is already open, the single-instance plugin forwards the second launch's argv to
// the running window (see lib.rs) so it switches repo instead of stacking windows.

use serde_json::{json, Value};
use std::path::PathBuf;
use std::sync::Mutex;
use tauri::AppHandle;

/// The repo path passed on cold launch, taken once by the frontend on startup.
#[derive(Default)]
pub struct InitialRepo(pub Mutex<Option<String>>);

/// The first existing directory argument (skipping argv[0] and flags), absolute.
pub fn repo_from_argv(argv: &[String]) -> Option<String> {
    argv.iter()
        .skip(1)
        .filter(|a| !a.starts_with('-'))
        .map(PathBuf::from)
        .find(|p| p.is_dir())
        .and_then(|p| std::fs::canonicalize(&p).ok())
        .map(|p| p.to_string_lossy().into_owned())
}

fn shim_path() -> Option<PathBuf> {
    std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".local/bin/locke"))
}

/// Single-quote a string for safe embedding in the generated /bin/sh shim.
fn sh_squote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Whether the `locke` shim is installed, plus its path (for the Settings UI).
pub fn status() -> Value {
    let path = shim_path();
    let installed = path.as_ref().map(|p| p.exists()).unwrap_or(false);
    json!({
        "installed": installed,
        "path": path.map(|p| p.to_string_lossy().into_owned()).unwrap_or_default(),
    })
}

/// Install the `locke` shim to ~/.local/bin, pointing at the running app binary.
/// Re-running updates it (e.g. after the app moves). Idempotent.
pub fn install(_app: &AppHandle) -> Result<(), String> {
    let shim = shim_path().ok_or("no $HOME to install into")?;
    let bin = std::env::current_exe().map_err(|e| format!("resolve app binary: {e}"))?;
    let dir = shim.parent().ok_or("bad shim path")?;
    std::fs::create_dir_all(dir).map_err(|e| format!("create {}: {e}", dir.display()))?;

    let script = format!(
        "#!/bin/sh\n\
         # Locke CLI — open a folder in Locke. Generated by Locke; re-run Install to update.\n\
         BIN={bin}\n\
         target=\"${{1:-.}}\"\n\
         dir=\"$(cd \"$target\" 2>/dev/null && pwd)\" || {{ echo \"locke: no such directory: $target\" >&2; exit 1; }}\n\
         nohup \"$BIN\" \"$dir\" >/dev/null 2>&1 &\n",
        bin = sh_squote(&bin.to_string_lossy()),
    );
    std::fs::write(&shim, script).map_err(|e| format!("write {}: {e}", shim.display()))?;

    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(&shim, std::fs::Permissions::from_mode(0o755))
        .map_err(|e| format!("chmod {}: {e}", shim.display()))?;
    Ok(())
}

/// Remove the `locke` shim. No-op if it isn't there.
pub fn uninstall() -> Result<(), String> {
    if let Some(p) = shim_path() {
        if p.exists() {
            std::fs::remove_file(&p).map_err(|e| format!("remove {}: {e}", p.display()))?;
        }
    }
    Ok(())
}
