// Theme palettes + runtime application. v1.4 introduces selectable themes; the
// design tokens in `tokens.ts` are CSS variables (`--lk-*`), and a theme is just a
// full set of values for them. `applyTheme` writes those onto <body> so the app
// re-skins live with no re-render. Palettes below were generated from the original
// Midnight values (see git history) and hand-tuned per theme — edit values here.
//
// Accents are largely shared so the app keeps its identity across dark themes;
// Paper is the one light theme and overrides the text ramp + accent-text shades.

// AUTO-AUTHORED palettes — see theme/themes.ts header. Edit values here.
export const THEME_VARS = [
  "appBg",
  "titlebarBg",
  "sidebarBg",
  "panelBg",
  "panelHeaderBg",
  "inputBg",
  "popoverBg",
  "navPillBg",
  "terminalBg",
  "chipBg",
  "rowActiveBg",
  "rowHoverBg",
  "borderPopover",
  "borderRail",
  "borderSubtle",
  "borderPanel",
  "borderRow",
  "borderRowFaint",
  "borderRowFaint2",
  "borderRowFaint3",
  "borderRail2",
  "borderInput",
  "borderChip",
  "borderChip2",
  "borderRow2",
  "textBright",
  "text",
  "textCode",
  "textSoft",
  "textMuted",
  "textDim",
  "textFaint",
  "textFainter",
  "textGhost",
  "lineNo",
  "violet",
  "violetHover",
  "violetLogo",
  "violetLight",
  "violetSoft",
  "teal",
  "green",
  "greenText",
  "red",
  "amber",
  "blue",
  "blueRun",
  "approved",
  "codex",
  "scrim",
  "syn-kw",
  "syn-str",
  "syn-com",
  "syn-num",
  "syn-fn",
  "syn-type",
  "syn-punct",
  "syn-id",
] as const;

export const THEMES = {
  midnight: {
    label: "Midnight",
    vars: {
      "appBg": "#0a0c11",
      "titlebarBg": "#0c0e13",
      "sidebarBg": "#0b0d12",
      "panelBg": "#0e1117",
      "panelHeaderBg": "#0c0f15",
      "inputBg": "#0a0c11",
      "popoverBg": "#10131a",
      "navPillBg": "#090b0f",
      "terminalBg": "#06070a",
      "chipBg": "#12161d",
      "rowActiveBg": "#1b2230",
      "rowHoverBg": "#11151d",
      "borderPopover": "#2a3140",
      "borderRail": "#1c2330",
      "borderSubtle": "#1a1f29",
      "borderPanel": "#1f2733",
      "borderRow": "#1a212b",
      "borderRowFaint": "#131820",
      "borderRowFaint2": "#19202b",
      "borderRowFaint3": "#141a22",
      "borderRail2": "#161c25",
      "borderInput": "#2c333f",
      "borderChip": "#232a35",
      "borderChip2": "#242a35",
      "borderRow2": "#181d26",
      "textBright": "#f3f5f8",
      "text": "#e7eaf0",
      "textCode": "#dbe0e9",
      "textSoft": "#cdd3de",
      "textMuted": "#bcc4d2",
      "textDim": "#aeb6c4",
      "textFaint": "#8b94a6",
      "textFainter": "#6b7484",
      "textGhost": "#5f6878",
      "lineNo": "#465062",
      "violet": "#7b6cff",
      "violetHover": "#8b7dff",
      "violetLogo": "#8b7bff",
      "violetLight": "#b3a8ff",
      "violetSoft": "#c0a9ff",
      "teal": "#3fd0c0",
      "green": "#43c46b",
      "greenText": "#a5e08a",
      "red": "#f0616d",
      "amber": "#f0b86e",
      "blue": "#82aaff",
      "blueRun": "#5aa9ff",
      "approved": "#a78bff",
      "codex": "#c0a9ff",
      "scrim": "rgba(0,0,0,.5)",
      "syn-kw": "#ff7b9c",
      "syn-str": "#a5e08a",
      "syn-com": "#5e6878",
      "syn-num": "#f0b86e",
      "syn-fn": "#82aaff",
      "syn-type": "#5cd0e6",
      "syn-punct": "#7f8a9e",
      "syn-id": "#cdd3de",
    },
  },
  slate: {
    label: "Slate",
    vars: {
      "appBg": "#18191d",
      "titlebarBg": "#191b1f",
      "sidebarBg": "#191a1e",
      "panelBg": "#1c1e22",
      "panelHeaderBg": "#1a1c20",
      "inputBg": "#18191d",
      "popoverBg": "#1e2125",
      "navPillBg": "#16181b",
      "terminalBg": "#131417",
      "chipBg": "#212328",
      "rowActiveBg": "#2d3137",
      "rowHoverBg": "#202327",
      "borderPopover": "#3d424b",
      "borderRail": "#30343b",
      "borderSubtle": "#2c2f36",
      "borderPanel": "#33363e",
      "borderRow": "#2d3037",
      "borderRowFaint": "#25272d",
      "borderRowFaint2": "#2c3036",
      "borderRowFaint3": "#26292f",
      "borderRail2": "#282b31",
      "borderInput": "#3e434c",
      "borderChip": "#353941",
      "borderChip2": "#363a42",
      "borderRow2": "#2a2d33",
      "textBright": "#f3f5f8",
      "text": "#e7eaf0",
      "textCode": "#dbe0e9",
      "textSoft": "#cdd3de",
      "textMuted": "#bcc4d2",
      "textDim": "#aeb6c4",
      "textFaint": "#8b94a6",
      "textFainter": "#6b7484",
      "textGhost": "#5f6878",
      "lineNo": "#465062",
      "violet": "#7b6cff",
      "violetHover": "#8b7dff",
      "violetLogo": "#8b7bff",
      "violetLight": "#b3a8ff",
      "violetSoft": "#c0a9ff",
      "teal": "#3fd0c0",
      "green": "#43c46b",
      "greenText": "#a5e08a",
      "red": "#f0616d",
      "amber": "#f0b86e",
      "blue": "#82aaff",
      "blueRun": "#5aa9ff",
      "approved": "#a78bff",
      "codex": "#c0a9ff",
      "scrim": "rgba(0,0,0,.5)",
      "syn-kw": "#ff7b9c",
      "syn-str": "#a5e08a",
      "syn-com": "#5e6878",
      "syn-num": "#f0b86e",
      "syn-fn": "#82aaff",
      "syn-type": "#5cd0e6",
      "syn-punct": "#7f8a9e",
      "syn-id": "#cdd3de",
    },
  },
  nord: {
    label: "Nord",
    vars: {
      "appBg": "#13161a",
      "titlebarBg": "#15181c",
      "sidebarBg": "#14171b",
      "panelBg": "#171b20",
      "panelHeaderBg": "#15191d",
      "inputBg": "#13161a",
      "popoverBg": "#191d23",
      "navPillBg": "#121418",
      "terminalBg": "#0e1014",
      "chipBg": "#1b2026",
      "rowActiveBg": "#272d36",
      "rowHoverBg": "#1b1f25",
      "borderPopover": "#39424b",
      "borderRail": "#2c333a",
      "borderSubtle": "#282e35",
      "borderPanel": "#2e363d",
      "borderRow": "#292f36",
      "borderRowFaint": "#21262c",
      "borderRowFaint2": "#282f35",
      "borderRowFaint3": "#22282d",
      "borderRail2": "#242a30",
      "borderInput": "#39424c",
      "borderChip": "#313941",
      "borderChip2": "#313941",
      "borderRow2": "#262c32",
      "textBright": "#f3f5f8",
      "text": "#e7eaf0",
      "textCode": "#dbe0e9",
      "textSoft": "#cdd3de",
      "textMuted": "#bcc4d2",
      "textDim": "#aeb6c4",
      "textFaint": "#8b94a6",
      "textFainter": "#6b7484",
      "textGhost": "#5f6878",
      "lineNo": "#465062",
      "violet": "#b48ead",
      "violetHover": "#c79cc0",
      "violetLogo": "#8b7bff",
      "violetLight": "#c0a9d6",
      "violetSoft": "#c0a9ff",
      "teal": "#88c0d0",
      "green": "#a3be8c",
      "greenText": "#a5e08a",
      "red": "#bf616a",
      "amber": "#ebcb8b",
      "blue": "#81a1c1",
      "blueRun": "#5aa9ff",
      "approved": "#b48ead",
      "codex": "#b48ead",
      "scrim": "rgba(0,0,0,.5)",
      "syn-kw": "#ff7b9c",
      "syn-str": "#a5e08a",
      "syn-com": "#5e6878",
      "syn-num": "#f0b86e",
      "syn-fn": "#82aaff",
      "syn-type": "#5cd0e6",
      "syn-punct": "#7f8a9e",
      "syn-id": "#cdd3de",
    },
  },
  ember: {
    label: "Ember",
    vars: {
      "appBg": "#16120f",
      "titlebarBg": "#181411",
      "sidebarBg": "#171310",
      "panelBg": "#1c1713",
      "panelHeaderBg": "#191512",
      "inputBg": "#16120f",
      "popoverBg": "#1f1915",
      "navPillBg": "#14110e",
      "terminalBg": "#0f0d0b",
      "chipBg": "#221c17",
      "rowActiveBg": "#322923",
      "rowHoverBg": "#211b17",
      "borderPopover": "#493e35",
      "borderRail": "#382f28",
      "borderSubtle": "#332b25",
      "borderPanel": "#3b322b",
      "borderRow": "#342c26",
      "borderRowFaint": "#29231e",
      "borderRowFaint2": "#332b25",
      "borderRowFaint3": "#2b241f",
      "borderRail2": "#2e2721",
      "borderInput": "#4a3e36",
      "borderChip": "#3f352e",
      "borderChip2": "#3f352e",
      "borderRow2": "#302823",
      "textBright": "#f3f5f8",
      "text": "#e7eaf0",
      "textCode": "#dbe0e9",
      "textSoft": "#cdd3de",
      "textMuted": "#bcc4d2",
      "textDim": "#aeb6c4",
      "textFaint": "#8b94a6",
      "textFainter": "#6b7484",
      "textGhost": "#5f6878",
      "lineNo": "#465062",
      "violet": "#e0975f",
      "violetHover": "#eaa873",
      "violetLogo": "#8b7bff",
      "violetLight": "#b3a8ff",
      "violetSoft": "#c0a9ff",
      "teal": "#5ec8b0",
      "green": "#43c46b",
      "greenText": "#a5e08a",
      "red": "#f0616d",
      "amber": "#f0b86e",
      "blue": "#82aaff",
      "blueRun": "#5aa9ff",
      "approved": "#e0975f",
      "codex": "#e6a972",
      "scrim": "rgba(0,0,0,.5)",
      "syn-kw": "#ff7b9c",
      "syn-str": "#a5e08a",
      "syn-com": "#5e6878",
      "syn-num": "#f0b86e",
      "syn-fn": "#82aaff",
      "syn-type": "#5cd0e6",
      "syn-punct": "#7f8a9e",
      "syn-id": "#cdd3de",
    },
  },
  paper: {
    label: "Paper",
    vars: {
      "appBg": "#f4f2ec",
      "titlebarBg": "#efece4",
      "sidebarBg": "#f0ede6",
      "panelBg": "#faf8f3",
      "panelHeaderBg": "#f1eee7",
      "inputBg": "#ffffff",
      "popoverBg": "#ffffff",
      "navPillBg": "#e8e4da",
      "terminalBg": "#f6f4ee",
      "chipBg": "#efece4",
      "rowActiveBg": "#e6e1d6",
      "rowHoverBg": "#efece4",
      "borderPopover": "#d3ccbe",
      "borderRail": "#ddd6c8",
      "borderSubtle": "#e2dccf",
      "borderPanel": "#dcd5c7",
      "borderRow": "#e2dccf",
      "borderRowFaint": "#e8e2d6",
      "borderRowFaint2": "#e4ded2",
      "borderRowFaint3": "#eae4d8",
      "borderRail2": "#e6e0d3",
      "borderInput": "#cfc8ba",
      "borderChip": "#ddd6c8",
      "borderChip2": "#d9d2c4",
      "borderRow2": "#e4ded2",
      "textBright": "#1c1f24",
      "text": "#2b2f36",
      "textCode": "#33373f",
      "textSoft": "#3f444c",
      "textMuted": "#4d525c",
      "textDim": "#5a606b",
      "textFaint": "#787f8b",
      "textFainter": "#949aa6",
      "textGhost": "#a8aeb9",
      "lineNo": "#b9bdc7",
      "violet": "#6a5bf0",
      "violetHover": "#5b4ce0",
      "violetLogo": "#6a5bf0",
      "violetLight": "#6f5fd6",
      "violetSoft": "#7a63c8",
      "teal": "#1f9e90",
      "green": "#2f9e4f",
      "greenText": "#3a8a2f",
      "red": "#d9434f",
      "amber": "#c4791a",
      "blue": "#3a6fd0",
      "blueRun": "#3a6fd0",
      "approved": "#6a4fd0",
      "codex": "#7a5fc8",
      "scrim": "rgba(40,36,28,.35)",
      "syn-kw": "#c0395f",
      "syn-str": "#2f8a3f",
      "syn-com": "#9aa0aa",
      "syn-num": "#b5701a",
      "syn-fn": "#2f63c0",
      "syn-type": "#1f8aa0",
      "syn-punct": "#6a7280",
      "syn-id": "#33373f",
    },
  },
} as const;
export type ThemeId = keyof typeof THEMES;
export const THEME_IDS = Object.keys(THEMES) as ThemeId[];
export const DEFAULT_THEME: ThemeId = "midnight";
// Paper is the only light theme; used to set `color-scheme` so native scrollbars
// and form controls adapt.
const LIGHT_THEMES = new Set<ThemeId>(["paper"]);

export function isThemeId(v: unknown): v is ThemeId {
  return typeof v === "string" && v in THEMES;
}

/** Apply a theme by writing its CSS variables onto <body>. Safe to call before
 *  React mounts (used by the inline boot script) and on every theme change. */
export function applyTheme(id: ThemeId): void {
  if (typeof document === "undefined") return;
  const theme = THEMES[id] ?? THEMES[DEFAULT_THEME];
  const body = document.body;
  for (const name of THEME_VARS) {
    body.style.setProperty(`--lk-${name}`, theme.vars[name]);
  }
  body.dataset.theme = id;
  body.style.colorScheme = LIGHT_THEMES.has(id) ? "light" : "dark";
}
