import type { Check } from "@locke/core";
import { useStore } from "../state/store.js";
import { color, font } from "../theme/tokens.js";
import { statusMeta, fileStatusMeta, agentChipStyle, addStr, delStr, currentReview } from "../lib/meta.js";
import { HoverButton, HoverDiv } from "../components/primitives.js";
import { VerdictBanner } from "../components/VerdictBanner.js";
import {
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowRightIcon,
  CheckIcon,
  CheckCircleIcon,
  XCircleIcon,
  SpinnerIcon,
  PlayIcon,
  InfoIcon,
  CommitIcon,
  SparkleIcon,
} from "../components/icons.js";

const label = (text: string, mb = 10): React.ReactNode => (
  <div style={{ fontSize: 10, fontWeight: 600, letterSpacing: ".8px", color: color.textGhost, marginBottom: mb }}>
    {text}
  </div>
);

const cardHeader: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "12px 16px",
  borderBottom: "1px solid #1a212b",
  background: color.panelHeaderBg,
};

const card: React.CSSProperties = {
  border: `1px solid ${color.borderPanel}`,
  borderRadius: 13,
  overflow: "hidden",
  background: color.panelBg,
};

const checkInput: React.CSSProperties = {
  boxSizing: "border-box",
  background: color.appBg,
  border: "1px solid #2c333f",
  borderRadius: 7,
  padding: "7px 10px",
  color: color.text,
  fontFamily: font.sans,
  fontSize: 12.5,
  outline: "none",
};

function Sidebar() {
  const reviews = useStore((s) => s.reviews);
  const selectedPR = useStore((s) => s.selectedPR);
  const goList = useStore((s) => s.go);
  const pr = currentReview(reviews, selectedPR);
  const sm = statusMeta(pr.status);
  const agentModel = pr.model ?? "human";

  return (
    <div
      style={{
        width: 300,
        flex: "none",
        background: color.sidebarBg,
        borderRight: `1px solid ${color.borderSubtle}`,
        overflowY: "auto",
        padding: "16px 16px 28px",
      }}
    >
      <HoverButton
        onClick={() => goList("list")}
        style={{
          display: "flex",
          alignItems: "center",
          gap: 7,
          background: "transparent",
          border: "none",
          cursor: "pointer",
          color: color.textFaint,
          fontFamily: font.sans,
          fontSize: 12,
          padding: 0,
          marginBottom: 18,
        }}
        hoverStyle={{ color: color.textMuted }}
      >
        <ChevronLeftIcon size={13} color="currentColor" />
        Back to queue
      </HoverButton>

      {label("STATUS", 9)}
      <div
        style={{
          display: "inline-flex",
          alignItems: "center",
          gap: 7,
          padding: "5px 12px",
          borderRadius: 20,
          fontSize: 12,
          fontWeight: 600,
          marginBottom: 22,
          color: sm.col,
          background: sm.bg,
          border: `1px solid ${sm.bd}`,
        }}
      >
        <span style={{ width: 8, height: 8, borderRadius: "50%", background: sm.col }} />
        {sm.label}
      </div>

      {label("GENERATED BY")}
      <div
        style={{
          display: "flex",
          gap: 11,
          padding: 12,
          background: color.panelBg,
          border: `1px solid ${color.borderPanel}`,
          borderRadius: 11,
          marginBottom: 22,
        }}
      >
        <span
          style={{
            width: 34,
            height: 34,
            flex: "none",
            borderRadius: 9,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: 12,
            fontWeight: 700,
            ...agentChipStyle(pr.isAgent),
          }}
        >
          {pr.initials}
        </span>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: color.text }}>{pr.agent}</div>
          <div style={{ fontSize: 11.5, color: color.textFainter, fontFamily: font.mono, marginTop: 1 }}>
            {agentModel}
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 5, marginTop: 8, fontSize: 11, color: color.teal }}>
            <SparkleIcon size={11} color={color.teal} />
            3 commits, 2 follow-up runs
          </div>
        </div>
      </div>

      {label("REVIEWERS")}
      <div style={{ display: "flex", alignItems: "center", gap: 9, marginBottom: 22 }}>
        <span
          style={{
            width: 26,
            height: 26,
            borderRadius: "50%",
            background: "rgba(123,108,255,.16)",
            border: "1px solid rgba(123,108,255,.34)",
            color: color.violetLight,
            fontSize: 10,
            fontWeight: 700,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          YO
        </span>
        <span style={{ fontSize: 12.5, color: color.textMuted }}>You</span>
        <span style={{ fontSize: 11, color: color.textFainter, marginLeft: "auto" }}>awaiting review</span>
      </div>

      {label("LABELS")}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 7, marginBottom: 22 }}>
        <LabelChip text="webhooks" col="#82aaff" rgb="130,170,255" />
        <LabelChip text="bug" col="#f0616d" rgb="240,97,109" />
        <LabelChip text="agent-authored" col="#3fd0c0" rgb="63,208,192" />
      </div>

      {label("BRANCH")}
      <div style={{ display: "flex", flexDirection: "column", gap: 9, fontFamily: font.mono, fontSize: 11.5 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, color: color.textFaint }}>
          <span style={{ color: color.textGhost, width: 30 }}>head</span>
          <span style={{ color: color.greenText }}>{pr.branch}</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8, color: color.textFaint }}>
          <span style={{ color: color.textGhost, width: 30 }}>base</span>
          <span style={{ color: color.blue }}>{pr.base}</span>
        </div>
      </div>
    </div>
  );
}

function LabelChip({ text, col, rgb }: { text: string; col: string; rgb: string }) {
  return (
    <span
      style={{
        fontSize: 11,
        color: col,
        background: `rgba(${rgb},.1)`,
        border: `1px solid rgba(${rgb},.26)`,
        borderRadius: 20,
        padding: "2px 10px",
      }}
    >
      {text}
    </span>
  );
}

function Main() {
  const reviews = useStore((s) => s.reviews);
  const selectedPR = useStore((s) => s.selectedPR);
  const files = useStore((s) => s.files);
  const detail = useStore((s) => s.detail);
  const testsRunning = useStore((s) => s.testsRunning);
  const testsRan = useStore((s) => s.testsRan);
  const repoPath = useStore((s) => s.repoPath);
  const liveChecks = useStore((s) => s.liveChecks);
  const checkSpecs = useStore((s) => s.checkSpecs);
  const checksAreOverride = useStore((s) => s.checksAreOverride);
  const editingChecks = useStore((s) => s.editingChecks);
  const toggleEditChecks = useStore((s) => s.toggleEditChecks);
  const updateCheckSpec = useStore((s) => s.updateCheckSpec);
  const addCheckSpec = useStore((s) => s.addCheckSpec);
  const removeCheckSpec = useStore((s) => s.removeCheckSpec);
  const autoDetectChecks = useStore((s) => s.autoDetectChecks);
  const onApprove = useStore((s) => s.setVerdict);
  const approveAndPush = useStore((s) => s.approveAndPush);
  const onRunTests = useStore((s) => s.runTests);
  const goReview = useStore((s) => s.goReview);
  const setState = useStore.setState;

  const pr = currentReview(reviews, selectedPR);
  const sm = statusMeta(pr.status);

  // Mock mode shows the design's sample checks; live mode shows auto-detected,
  // really-executed results (empty until the first run).
  const mockChecks: Check[] = [
    { label: "ESLint", detail: "0 problems", status: "pass" },
    { label: "tsc --noEmit", detail: "no type errors", status: "pass" },
    {
      label: "Unit tests",
      detail: testsRunning ? "running…" : testsRan ? "142 passed in 3.1s" : "142 passed",
      status: testsRunning ? "running" : "pass",
    },
    { label: "Build", detail: "bundle ok", status: "pass" },
  ];
  const checks: Check[] = repoPath ? liveChecks : mockChecks;

  return (
    <div style={{ flex: 1, display: "flex", flexDirection: "column", minHeight: 0, background: color.appBg }}>
      <div style={{ padding: "22px 32px 18px", borderBottom: `1px solid ${color.borderSubtle}` }}>
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 24 }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ fontSize: 12, color: color.textFainter, fontFamily: font.mono, marginBottom: 7 }}>#{pr.id}</div>
            <h1 style={{ margin: 0, fontSize: 22, fontWeight: 700, letterSpacing: "-.4px", color: color.textBright, lineHeight: 1.25 }}>
              {pr.title}
            </h1>
            <div style={{ display: "flex", alignItems: "center", gap: 10, marginTop: 13, flexWrap: "wrap", fontSize: 12 }}>
              <span
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 6,
                  padding: "4px 11px",
                  borderRadius: 20,
                  fontWeight: 600,
                  color: sm.col,
                  background: sm.bg,
                  border: `1px solid ${sm.bd}`,
                }}
              >
                <span style={{ width: 7, height: 7, borderRadius: "50%", background: sm.col }} />
                {sm.label}
              </span>
              <span style={{ fontFamily: font.mono, color: color.greenText }}>{pr.branch}</span>
              <ArrowRightIcon size={13} color={color.textGhost} />
              <span style={{ fontFamily: font.mono, color: color.blue }}>{pr.base}</span>
            </div>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 9, flex: "none" }}>
            <HoverButton
              onClick={onRunTests}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 7,
                padding: "9px 13px",
                background: "#12161d",
                border: "1px solid #2a3140",
                borderRadius: 9,
                color: color.textSoft,
                fontFamily: font.sans,
                fontSize: 12.5,
                fontWeight: 500,
                cursor: "pointer",
              }}
              hoverStyle={{ borderColor: "#37404f", background: "#161b24" }}
            >
              {testsRunning ? (
                <>
                  <SpinnerIcon size={13} color={color.blueRun} stroke={1.6} />
                  Running…
                </>
              ) : (
                <>
                  <PlayIcon size={13} color={color.textFaint} />
                  Run tests
                </>
              )}
            </HoverButton>
            <HoverButton
              onClick={() => onApprove("changes")}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 7,
                padding: "9px 13px",
                background: "transparent",
                border: "1px solid #38303a",
                borderRadius: 9,
                color: color.red,
                fontFamily: font.sans,
                fontSize: 12.5,
                fontWeight: 600,
                cursor: "pointer",
              }}
              hoverStyle={{ background: "rgba(240,97,109,.08)", borderColor: "#5a3a42" }}
            >
              Request changes
            </HoverButton>
            <HoverButton
              onClick={() => void approveAndPush()}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 7,
                padding: "9px 15px",
                background: color.violet,
                border: `1px solid ${color.violet}`,
                borderRadius: 9,
                color: "#fff",
                fontFamily: font.sans,
                fontSize: 12.5,
                fontWeight: 600,
                cursor: "pointer",
                boxShadow: "0 2px 10px rgba(123,108,255,.25)",
              }}
              hoverStyle={{ background: color.violetHover }}
            >
              <CheckIcon size={13} color="#fff" />
              Approve &amp; push
            </HoverButton>
          </div>
        </div>
      </div>

      <div style={{ flex: 1, overflowY: "auto", padding: "24px 32px 40px" }}>
        <div style={{ maxWidth: 880, display: "flex", flexDirection: "column", gap: 18 }}>
          <VerdictBanner pr={pr} />

          {/* Prompt */}
          <div style={card}>
            <div style={cardHeader}>
              <SparkleIcon size={14} color={color.teal} />
              <span style={{ fontSize: 12.5, fontWeight: 600, color: color.textSoft }}>Prompt</span>
              <span style={{ fontSize: 11.5, color: color.textGhost, fontFamily: font.mono }}>
                You → {pr.agent} · {pr.model ?? "human"}
              </span>
            </div>
            <div
              style={{
                fontSize: 13.5,
                lineHeight: 1.6,
                color: color.textDim,
                fontStyle: "italic",
                borderLeft: `2px solid ${color.teal}`,
                margin: "14px 16px",
                background: "rgba(63,208,192,.03)",
                borderRadius: "0 8px 8px 0",
                padding: "13px 16px",
              }}
            >
              {detail.prompt}
            </div>
          </div>

          {/* Description */}
          <div style={card}>
            <div style={cardHeader}>
              <span style={{ fontSize: 12.5, fontWeight: 600, color: color.textSoft }}>Description</span>
              <span
                style={{
                  fontSize: 11,
                  color: color.teal,
                  background: "rgba(63,208,192,.1)",
                  border: "1px solid rgba(63,208,192,.26)",
                  borderRadius: 5,
                  padding: "1px 7px",
                  fontWeight: 600,
                }}
              >
                written by {pr.agent}
              </span>
            </div>
            <div style={{ padding: 17 }}>
              <p style={{ margin: "0 0 14px", fontSize: 14, lineHeight: 1.65, color: "#c2cad6" }}>{detail.summary}</p>
              <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 10 }}>
                {detail.bullets.map((b, i) => (
                  <li key={i} style={{ display: "flex", gap: 11, fontSize: 13.5, lineHeight: 1.55, color: color.textDim }}>
                    <span
                      style={{
                        flex: "none",
                        width: 18,
                        height: 18,
                        marginTop: 1,
                        borderRadius: 5,
                        background: "rgba(67,196,107,.1)",
                        border: "1px solid rgba(67,196,107,.26)",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                      }}
                    >
                      <CheckIcon size={11} color={color.green} stroke={2} />
                    </span>
                    {b}
                  </li>
                ))}
              </ul>
              <div
                style={{
                  display: "flex",
                  gap: 10,
                  marginTop: 16,
                  padding: "11px 14px",
                  background: "rgba(130,170,255,.05)",
                  border: "1px solid rgba(130,170,255,.16)",
                  borderRadius: 9,
                  fontSize: 12.5,
                  color: "#9fb4d8",
                }}
              >
                <InfoIcon size={15} color={color.blue} style={{ flex: "none", marginTop: 1 }} />
                {detail.note}
              </div>
            </div>
          </div>

          {/* Checks */}
          <div style={card}>
            <div style={{ ...cardHeader, justifyContent: "space-between" }}>
              <div style={{ display: "flex", alignItems: "center", gap: 9 }}>
                <CheckCircleIcon size={15} color={color.green} />
                <span style={{ fontSize: 12.5, fontWeight: 600, color: color.textSoft }}>Checks</span>
                {repoPath && checksAreOverride && (
                  <span
                    style={{
                      fontSize: 10,
                      color: color.violetSoft,
                      background: "rgba(123,108,255,.1)",
                      border: "1px solid rgba(123,108,255,.26)",
                      borderRadius: 5,
                      padding: "1px 7px",
                      fontWeight: 600,
                    }}
                  >
                    custom
                  </span>
                )}
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
                {repoPath && (
                  <HoverButton
                    onClick={toggleEditChecks}
                    style={{ fontSize: 11.5, color: editingChecks ? color.violetSoft : color.textFaint, background: "transparent", border: "none", cursor: "pointer", fontFamily: font.sans }}
                    hoverStyle={{ color: color.textSoft }}
                  >
                    {editingChecks ? "Done" : "Edit"}
                  </HoverButton>
                )}
                <HoverButton
                  onClick={onRunTests}
                  style={{ fontSize: 11.5, color: color.textFaint, background: "transparent", border: "none", cursor: "pointer", fontFamily: font.sans }}
                  hoverStyle={{ color: color.textSoft }}
                >
                  Re-run locally
                </HoverButton>
              </div>
            </div>

            {repoPath && editingChecks ? (
              <div style={{ padding: "12px 16px", display: "flex", flexDirection: "column", gap: 9 }}>
                {checkSpecs.map((c, i) => (
                  <div key={i} style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <input
                      value={c.label}
                      onChange={(e) => updateCheckSpec(i, "label", e.target.value)}
                      placeholder="Label"
                      style={{ ...checkInput, width: 130, flex: "none" }}
                    />
                    <input
                      value={c.command}
                      onChange={(e) => updateCheckSpec(i, "command", e.target.value)}
                      placeholder="shell command"
                      style={{ ...checkInput, flex: 1, fontFamily: font.mono }}
                    />
                    <button
                      onClick={() => removeCheckSpec(i)}
                      title="Remove"
                      style={{ flex: "none", width: 28, height: 28, borderRadius: 7, border: "1px solid #2c333f", background: "transparent", color: color.textFainter, cursor: "pointer" }}
                    >
                      ×
                    </button>
                  </div>
                ))}
                <div style={{ display: "flex", gap: 10, marginTop: 2 }}>
                  <HoverButton
                    onClick={addCheckSpec}
                    style={{ fontSize: 12, color: color.textSoft, background: "#12161d", border: "1px solid #2a3140", borderRadius: 7, padding: "6px 11px", cursor: "pointer", fontFamily: font.sans }}
                    hoverStyle={{ borderColor: "#37404f" }}
                  >
                    + Add check
                  </HoverButton>
                  <HoverButton
                    onClick={() => void autoDetectChecks()}
                    style={{ fontSize: 12, color: color.textFaint, background: "transparent", border: "1px solid #2a3140", borderRadius: 7, padding: "6px 11px", cursor: "pointer", fontFamily: font.sans }}
                    hoverStyle={{ color: color.textSoft, borderColor: "#37404f" }}
                  >
                    Reset to auto-detect
                  </HoverButton>
                </div>
              </div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column" }}>
                {checks.length === 0 && (
                  <div style={{ padding: "13px 16px", fontSize: 12.5, color: color.textFainter }}>
                    {testsRunning ? "Detecting checks…" : "Run tests to detect and run checks from this repo's tooling."}
                  </div>
                )}
                {checks.map((c) => {
                  const dc = c.status === "pass" ? color.green : c.status === "running" ? color.blueRun : color.red;
                  return (
                    <div key={c.label} style={{ display: "flex", alignItems: "center", gap: 11, padding: "11px 16px", borderBottom: "1px solid #131820" }}>
                      {c.status === "running" ? (
                        <SpinnerIcon size={14} color={color.blueRun} stroke={1.7} />
                      ) : c.status === "fail" ? (
                        <XCircleIcon size={14} color={color.red} stroke={1.7} />
                      ) : (
                        <CheckCircleIcon size={14} color={color.green} stroke={1.7} />
                      )}
                      <span style={{ fontSize: 13, color: color.textCode, fontFamily: font.mono, flex: 1 }}>{c.label}</span>
                      <span style={{ fontSize: 12, color: dc }}>{c.detail}</span>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Files changed */}
          <div style={card}>
            <div style={{ ...cardHeader, justifyContent: "space-between" }}>
              <span style={{ fontSize: 12.5, fontWeight: 600, color: color.textSoft }}>Files changed</span>
              <HoverButton
                onClick={goReview}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 6,
                  fontSize: 12,
                  fontWeight: 600,
                  color: "#fff",
                  background: color.violet,
                  border: `1px solid ${color.violet}`,
                  borderRadius: 8,
                  padding: "6px 13px",
                  cursor: "pointer",
                  fontFamily: font.sans,
                }}
                hoverStyle={{ background: color.violetHover }}
              >
                Review changes
                <ChevronRightIcon size={12} color="#fff" stroke={1.6} />
              </HoverButton>
            </div>
            <div>
              {files.map((f, i) => {
                const fs = fileStatusMeta(f.st);
                return (
                  <HoverDiv
                    key={f.path}
                    onClick={() => setState({ view: "review", selectedFile: i })}
                    style={{ display: "flex", alignItems: "center", gap: 11, padding: "11px 16px", borderBottom: "1px solid #131820", cursor: "pointer" }}
                    hoverStyle={{ background: "#11151d" }}
                  >
                    <span
                      style={{
                        width: 17,
                        height: 17,
                        flex: "none",
                        borderRadius: 4,
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        fontSize: 9.5,
                        fontWeight: 700,
                        border: "1px solid currentColor",
                        color: fs.col,
                        background: fs.bg,
                      }}
                    >
                      {f.st}
                    </span>
                    <span style={{ flex: 1, fontSize: 12.5, color: color.textCode, fontFamily: font.mono }}>{f.path}</span>
                    <span style={{ fontFamily: font.mono, fontSize: 11.5, color: color.green }}>{addStr(f.add)}</span>
                    <span style={{ fontFamily: font.mono, fontSize: 11.5, color: color.red }}>{delStr(f.del)}</span>
                    <ChevronRightIcon size={13} color="#454d5b" />
                  </HoverDiv>
                );
              })}
            </div>
          </div>

          {/* Commits */}
          <div style={card}>
            <div style={cardHeader}>
              <CommitIcon size={14} color={color.textFaint} />
              <span style={{ fontSize: 12.5, fontWeight: 600, color: color.textSoft }}>{detail.commits.length} commits</span>
            </div>
            <div>
              {detail.commits.map((c) => (
                <div key={c.sha} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", borderBottom: "1px solid #131820" }}>
                  <span
                    style={{
                      width: 26,
                      height: 26,
                      flex: "none",
                      borderRadius: 7,
                      background: "rgba(63,208,192,.12)",
                      border: "1px solid rgba(63,208,192,.28)",
                      color: color.teal,
                      fontSize: 9.5,
                      fontWeight: 700,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    {pr.initials}
                  </span>
                  <span style={{ flex: 1, fontSize: 13, color: color.textCode }}>{c.msg}</span>
                  <span
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      gap: 5,
                      fontSize: 10.5,
                      color: color.green,
                      background: "rgba(67,196,107,.08)",
                      border: "1px solid rgba(67,196,107,.22)",
                      borderRadius: 5,
                      padding: "2px 7px",
                    }}
                  >
                    <CheckIcon size={10} color={color.green} stroke={2} />
                    verified
                  </span>
                  <span style={{ fontFamily: font.mono, fontSize: 11.5, color: color.textFainter }}>{c.sha}</span>
                  <span style={{ fontSize: 11, color: color.textGhost }}>{c.time}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function OverviewView() {
  return (
    <>
      <Sidebar />
      <Main />
    </>
  );
}
