// Typed port of the design's built-in sample data. Used as the no-repo fallback
// so the UI is demoable before (and independent of) the real git backend.

import type { ChangedFile, Review, ReviewDetail, Thread } from "./types.js";

export const MOCK_REVIEWS: Review[] = [
  {
    id: "142",
    title: "Add idempotency keys to webhook retry handler",
    branch: "agent/webhook-idempotency",
    base: "main",
    agent: "Claude",
    model: "Sonnet 4.5",
    isAgent: true,
    initials: "CL",
    status: "ready",
    files: 4,
    add: 27,
    del: 9,
    comments: 3,
    checks: "pass",
    time: "8 min ago",
  },
  {
    id: "141",
    title: "Migrate user settings to a typed config schema",
    branch: "agent/typed-settings",
    base: "main",
    agent: "Claude",
    model: "Sonnet 4.5",
    isAgent: true,
    initials: "CL",
    status: "draft",
    files: 9,
    add: 214,
    del: 96,
    comments: 0,
    checks: "running",
    time: "40 min ago",
  },
  {
    id: "139",
    title: "Fix race condition in payment reconciliation job",
    branch: "agent/recon-lock",
    base: "main",
    agent: "Claude",
    model: "Sonnet 4.5",
    isAgent: true,
    initials: "CL",
    status: "changes",
    files: 3,
    add: 52,
    del: 41,
    comments: 5,
    checks: "fail",
    time: "2 hours ago",
  },
  {
    id: "137",
    title: "Update Stripe SDK to v14 and adjust types",
    branch: "agent/stripe-v14",
    base: "main",
    agent: "Codex",
    model: "gpt-5",
    isAgent: true,
    initials: "CX",
    status: "ready",
    files: 12,
    add: 88,
    del: 150,
    comments: 1,
    checks: "pass",
    time: "yesterday",
  },
  {
    id: "134",
    title: "Refactor: extract email templates into MJML",
    branch: "feat/mjml-emails",
    base: "main",
    agent: "maya",
    model: null,
    isAgent: false,
    initials: "MA",
    status: "ready",
    files: 6,
    add: 320,
    del: 210,
    comments: 3,
    checks: "pass",
    time: "2 days ago",
  },
];

export const MOCK_FILES: ChangedFile[] = [
  {
    path: "src/webhooks/retryHandler.ts",
    dir: "src/webhooks/",
    name: "retryHandler.ts",
    st: "M",
    add: 10,
    del: 6,
    hunks: [
      {
        hdr: "@@ -14,15 +14,24 @@ async handleEvent(event: WebhookEvent)",
        lines: [
          ["ctx", 14, 14, "  async handleEvent(event: WebhookEvent): Promise<void> {"],
          ["ctx", 15, 15, "    const delivery = await this.store.find(event.id);"],
          ["del", 16, 0, "    if (delivery) {"],
          ["del", 17, 0, "      return;"],
          ["del", 18, 0, "    }"],
          ["add", 0, 16, "    // Skip if we have already processed this delivery id"],
          ["add", 0, 17, "    const key = idempotencyKey(event);"],
          ["add", 0, 18, "    if (await this.store.has(key)) {"],
          ["add", 0, 19, "      this.logger.info('Duplicate webhook ignored', { key });"],
          ["add", 0, 20, "      return;"],
          ["add", 0, 21, "    }"],
          ["ctx", 19, 22, ""],
          ["ctx", 20, 23, "    const attempt = delivery?.attempts ?? 0;"],
          ["del", 21, 0, "    if (attempt > this.maxRetries) {"],
          ["del", 22, 0, "      this.deadLetter.push(event);"],
          ["add", 0, 24, "    if (attempt >= this.maxRetries) {"],
          ["add", 0, 25, "      await this.deadLetter.push(event, { reason: 'max_retries' });"],
          ["ctx", 23, 26, "      return;"],
          ["ctx", 24, 27, "    }"],
          ["ctx", 25, 28, ""],
          ["add", 0, 29, "    const backoff = this.backoffMs * Math.pow(2, attempt);"],
          ["add", 0, 30, "    await sleep(backoff);"],
          ["ctx", 26, 31, "    await this.dispatch(event);"],
          ["del", 27, 0, "    await this.store.save(event.id, attempt + 1);"],
          ["add", 0, 32, "    await this.store.save(key, attempt + 1);"],
          ["ctx", 28, 33, "  }"],
        ],
      },
    ],
  },
  {
    path: "src/webhooks/idempotency.ts",
    dir: "src/webhooks/",
    name: "idempotency.ts",
    st: "A",
    add: 10,
    del: 0,
    hunks: [
      {
        hdr: "@@ -0,0 +1,10 @@",
        lines: [
          ["add", 0, 1, "import { createHash } from 'crypto';"],
          ["add", 0, 2, "import { WebhookEvent } from '../types/webhook';"],
          ["add", 0, 3, ""],
          ["add", 0, 4, "// Derive a stable idempotency key from the event payload."],
          ["add", 0, 5, "// Stripe may redeliver the same event with a fresh request id,"],
          ["add", 0, 6, "// so we hash on the event identity instead of the body."],
          ["add", 0, 7, "export function idempotencyKey(event: WebhookEvent): string {"],
          ["add", 0, 8, "  const material = `${event.id}:${event.type}:${event.created}`;"],
          ["add", 0, 9, "  return createHash('sha256').update(material).digest('hex');"],
          ["add", 0, 10, "}"],
        ],
      },
    ],
  },
  {
    path: "src/types/webhook.ts",
    dir: "src/types/",
    name: "webhook.ts",
    st: "M",
    add: 3,
    del: 1,
    hunks: [
      {
        hdr: "@@ -8,4 +8,6 @@ export interface WebhookEvent",
        lines: [
          ["ctx", 8, 8, "export interface WebhookEvent {"],
          ["ctx", 9, 9, "  id: string;"],
          ["ctx", 10, 10, "  type: string;"],
          ["del", 11, 0, "  data: unknown;"],
          ["add", 0, 11, "  created: number;"],
          ["add", 0, 12, "  livemode: boolean;"],
          ["add", 0, 13, "  data: Record<string, unknown>;"],
          ["ctx", 12, 14, "}"],
        ],
      },
    ],
  },
  {
    path: "tests/webhooks/retry.test.ts",
    dir: "tests/webhooks/",
    name: "retry.test.ts",
    st: "M",
    add: 4,
    del: 2,
    hunks: [
      {
        hdr: "@@ -22,6 +22,12 @@ describe('WebhookRetryHandler')",
        lines: [
          ["ctx", 22, 22, "  it('ignores duplicate deliveries', async () => {"],
          ["del", 23, 0, "    const handler = new WebhookRetryHandler(store);"],
          ["add", 0, 23, "    const handler = new WebhookRetryHandler(store, { maxRetries: 3 });"],
          ["ctx", 24, 24, "    await handler.handleEvent(event);"],
          ["add", 0, 25, "    await handler.handleEvent(event);"],
          ["ctx", 25, 26, ""],
          ["del", 26, 0, "    expect(store.save).toHaveBeenCalledTimes(2);"],
          ["add", 0, 27, "    expect(store.save).toHaveBeenCalledTimes(1);"],
          ["add", 0, 28, "    expect(logger.info).toHaveBeenCalledWith('Duplicate webhook ignored');"],
          ["ctx", 27, 29, "  });"],
        ],
      },
    ],
  },
];

/** Narrative detail for the headline review (#142). */
export const MOCK_REVIEW_DETAIL: ReviewDetail = {
  prompt:
    "Our Stripe webhook handler occasionally processes the same event twice when Stripe redelivers it. Add idempotency so every event is handled exactly once, fall back to exponential backoff between retries, and cap attempts at maxRetries. Update the webhook types and tests to match.",
  summary:
    "This change makes webhook delivery idempotent. Stripe can redeliver the same event with a fresh request id, which previously caused duplicate side-effects in the retry handler.",
  bullets: [
    "New idempotency.ts derives a stable key from the event id, type and created timestamp — not the mutable request body.",
    "handleEvent now short-circuits when a key has already been seen, logging the duplicate instead of re-dispatching.",
    "The retry cap changed from > to >= so attempts are bounded at exactly maxRetries, with exponential backoff between tries.",
    "Types gain created / livemode fields and tests cover the concurrent-delivery case.",
  ],
  note:
    "No migration required — the Redis store adapter already exposes has / save inside a single transaction.",
  commits: [
    { sha: "9c1d77a", msg: "Update tests for idempotent handling", time: "8 min ago" },
    { sha: "4e8b210", msg: "Dedupe deliveries in retry handler", time: "14 min ago" },
    { sha: "a1f3c9d", msg: "Add idempotencyKey helper and webhook types", time: "19 min ago" },
  ],
};

export const MOCK_THREADS: Thread[] = [
  {
    id: 1,
    file: "src/webhooks/retryHandler.ts",
    lineId: "n18",
    resolved: false,
    items: [
      {
        author: "You",
        initials: "YO",
        isAgent: false,
        roleLabel: "AUTHOR",
        time: "3 min ago",
        body: "Is store.has atomic with the store.save below? If two webhooks land at the same instant we could still double-process.",
      },
      {
        author: "Claude",
        initials: "CL",
        isAgent: true,
        time: "2 min ago",
        body: "Good catch — has and save share a transaction in the Redis store adapter, so the check is atomic. I can add a test that fires two events concurrently if useful.",
      },
    ],
  },
  {
    id: 2,
    file: "src/webhooks/retryHandler.ts",
    lineId: "n24",
    resolved: true,
    items: [
      {
        author: "You",
        initials: "YO",
        isAgent: false,
        roleLabel: "AUTHOR",
        time: "5 min ago",
        body: "Switching > to >= changes behaviour on the boundary — intentional?",
      },
      {
        author: "Claude",
        initials: "CL",
        isAgent: true,
        time: "5 min ago",
        body: "Yes. Previously the Nth retry was let through; >= caps it at exactly maxRetries attempts.",
      },
    ],
  },
  {
    id: 3,
    file: "src/webhooks/idempotency.ts",
    lineId: "n7",
    resolved: false,
    items: [
      {
        author: "Claude",
        initials: "CL",
        isAgent: true,
        time: "8 min ago",
        body: "Note: hashing on id:type:created (not the raw body) keeps the key stable across Stripe redeliveries, which mutate the request field on every send.",
      },
    ],
  },
];
